workflows:
  ios-workflow:
    environment:
      ios_signing:
        # suas configurações de assinatura
      xcode: latest
    scripts:
      - name: Start iOS simulator
        script: |
          xcrun simctl list
          UDID=$(xcrun simctl list | grep -w "iPhone 14" | grep -E -o -i "([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})")
          xcrun simctl boot $UDID || true
          
      - name: Run tests on existing IPA
        script: |
          # Seu script de teste aqui
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
